name: Security Scan

on:
  push:
  pull_request:

jobs:
  check-filetypes:
    name: Check for Forbidden File Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run filetype check action
        uses: ./.github/actions/filetype-check
